name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish Self-Contained
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/
      
    - name: Create ZIP package
      run: |
        cd publish
        7z a -tzip ../OfflineEmailManager-${{ github.ref_name }}-win-x64.zip *
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          OfflineEmailManager-${{ github.ref_name }}-win-x64.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}